name: Deploy Micro-SASS Backend

on:
    push:
        branches:
        - main
        
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '24'
            
            - name: Install Bun
              run: npm install -g bun

            - name: Install dependencies
              run: bun install

            - name: Build the project
              run: bun run build

            # - name: Deploy to server
            #   env:
            #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            #     SERVER_USER: ${{ secrets.SERVER_USER }}
            #     SERVER_HOST: ${{ secrets.SERVER_HOST }}
            #     SERVER_PATH: ${{ secrets.SERVER_PATH }}
            #   run: |
            #         echo "$SSH_PRIVATE_KEY" > private_key.pem
            #         chmod 600 private_key.pem
            #         scp -i private_key.pem -r ./dist/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
            #         rm private_key.pem
